### ISSUE TITLE
Failed to remove file */tutorial1: Directory not empty

### ISSUE THREAD

**Issue by ProkopHapala** [gecko0307/dagon-tutorials#1]
Hi, 
I freshly installed Dlang dmd 2.094, and tried to compile this. I got following error:

```
prokop@prokop-Lenovo-ideapad-Y700-15ISK:~/git_SW/_Dlang/dagon-tutorials$ dub 
Performing "debug" build using /usr/bin/dmd for x86_64.
dlib 0.20.0: target for configuration "library" is up to date.
dagon 0.11.0: target for configuration "library" is up to date.
demo:tutorial1 0.10.0+commit.16.gadf70cd: target for configuration "" is up to date.
Failed to remove file /home/prokop/git_SW/_Dlang/dagon-tutorials/tutorial1: Directory not empty
```

**Comment by tombish** [comment]
The dub.json needs updating for Linux compatibility. "dub build" is trying to write the executable with the same name as an existing folder.

I simply moved all tutorial folders to a ./source directory then updated the json file to reflect changes.

**Comment by gecko0307** [comment]
Yeah, it's a major flaw 🙈. I'll move the sources.
