### ISSUE TITLE
Warning: no "input.conf" found

### ISSUE THREAD

**Issue by tombish** [gecko0307/dagon-tutorials#2]
On Linux running tutorials in project root directory produces:

`Warning: no "input.conf" found

Segmentation fault (core dumped)
`

**Comment by tombish** [comment]
I now understand that file is located in Dagon root directory. It is not immediately obvious this needs to be moved however.

**Comment by gecko0307** [comment]
Examples should work without input.conf, it is only needed for `scene.inputManager` events (i.e. device events mapped to logical names). Probably this crash is not related to input manager. Do you have SDL2 installed?

**Comment by tombish** [comment]
Apologies I was probably a bit hasty to file this issue.

I fixed it by, copying over the __internal folder from Dagon into tutorial data directory. The only thing to come out of this is perhaps Dagon should handle missing files more gracefully?
